# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 'Deploy to Azure App Service'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  AZURE_WEBAPP_NAME: 'PSDeployDemo'

jobs:
  build:
    env:
      BUILD_CONFIG: Release
      DOT_NET_VERSION: 10.0.x
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '${{ env.DOT_NET_VERSION }}'

    - name: Print build config
      run: echo "Build Config - $BUILD_CONFIG"

    - name: Print default environment variables of person or app that initiated workflow
    - run: echo "Workflow initiated by - $GITHUB_AUTHOR"
       
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration '${{ env.BUILD_CONFIG }}'
      
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

    - name: Deploy
      uses: Azure/webapps-deploy@v3.0.6
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        # slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
        
      
      
